api:
  url: http://localhost:8080/auto/getAll

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardealer
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

mq:
  status: 1
  host: localhost
  port: 1417
  channel: SYSTEM.DEF.SVRCONN
  queueManagerName: IBM2QMGR
  queueName: REQUEST
  clientTransport: false
